# Site settings
title: "My Food Safety Blog"
description: "A blog about food safety tips and tricks."
url: "https://<your-username>.github.io"

# Author settings
author:
  name: "Belal Abdelfattah"
  email: "your-email@example.com"
